### ISSUE TITLE
beberlei/assert 3.1 clashes with otphp

### ISSUE THREAD

**Issue by Firesphere** [Spomky-Labs/u2f-php#38]
**Describe the bug**
To use this module in combination with OTPHP, a composer requirement of beberlei/assert 3.1 clashes with OTPHP's requirement of beberlei/assert 2.4

**To Reproduce**
1. Require both OTPHP and u2f-php libraries in composer.json
2. Run `composer update`

**Expected behavior**
A successful installation of both libraries

**Comment by Spomky** [comment]
Hi @Firesphere,

Few hours ago, I updated OTPHP.
The last release (`v9.1.2`) now allows `beberlei/assert` v 3.x to be used.

I close this issue, but feel free to re-open if needed.

Please note that I created a new organization for this library.
If you are using the FIDO2 classes (namespace `U2FAuthentication\Fido2`), then I recommend  to move to the new package `web-auth/webauthn-lib`. The structure of the library is exactly the same. The new namespace is `Webauthn` instead of `U2FAuthentication\Fido2`

**Comment by Firesphere** [comment]
Hey @Spomky ,

Cheers for that! I'll move to the new place and start playing with OTPHP again as well. Thanks for fixing that fast!
